name_expe: flp/betavae
lr: 1.e-5
metrics: [reconstruction, sigma, norm_z, inde]
batch_size: 16
epoch: 1.e+5
seed: range(5)
dataset: 
  name: flatland/permutation
  m: 5
algo_specs:
  type: ae
  z_dim: 6
  image_specs:
    type: betavae
    beta: 1.e-3
    encoder_specs:
      type: conv2d
      hidden_channels: [32,64]
      kernel_size: 8
      pooling: null
      stride: 4
      padding: 2
      hidden_dim: [256]
    decoder_specs:
      type: deconv2d
      hidden_channels: [64,32]
      kernel_size: 8
      pooling: null
      stride: 4
      padding: 2
      hidden_dim: [256]
      final_activation_fn: sigmoid